name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'  # Specify the Ruby version you need

    - name: Install Bundler
      run: |
        gem install bundler -v '~> 2.4'
        bundle -v

    - name: Install Dependencies
      run: bundle install

    - name: Build Jekyll Site
      run: bundle exec jekyll build

    # Add additional steps as needed for deployment or other purposes
